namespace _0_Bit_Legend.Content;

public static class Credits
{
    public static string[] Lose => [
 "                                  THANKS   LINK,                                                      #",
 "                                  YOU'RE   THE   HERO   OF   HYRULE.                                  #",
 "                                                                                                      #",
@"                                            =<>=    /\                                                #",
 "                                            s^^s   /  |                                               #",
 "                                           ss~~ss |^  |                                               #",
 "                                           ~~~~~~ |_=_|                                               #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                              Awake,  my  young  Hero,                                                #",
 "                              For  peace  waits  not  on  the  morrow.                                #",
 "                              Now  go;  take  this  into  the  unknown:                               #",
 "                              It's  dangerous  to  go  alone!                                         #",
 "                                                                                                      #",
 "                              The  moon  sets,  and  the  moon  rises;                                #",
 "                              Darkness  only  this  night  comprises.                                 #",
 "                              What's  to  hope  with  a  quest  so  foggy?                            #",
 "                              It's  a  secret  to  everybody!                                         #",
 "                                                                                                      #",
 "                              Finally,  peace  returns  to  Hyrule.                                   #",
 "                              And  when  calamity  fell  successful,                                  #",
 "                              The  dream  of  a  legend  lifted  clear:                               #",
 "                              Another  quest  will  start  from  here!                                #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                           ==================== STAFF =====================                           #",
 "                           =                                              =                           #",
 "                           =                                              =                           #",
 "                           =      PRODUCER....     Jayden Newman          =                           #",
 "                           =                                              =                           #",
 "                           =                                              =                           #",
 "                           =      PROGRAMMER.....   Jayden Newman         =                           #",
 "                           =                                              =                           #",
 "                           =                                              =                           #",
 "                           =      DESIGNER....    Jayden Newman           =                           #",
 "                           =                                              =                           #",
 "                           =                                              =                           #",
 "                           =                 <***>                        =                           #",
 "                           =          FFF     S^SSS>                      =                           #",
 "                           =          FFF     *S  SS>                     =                           #",
 "                           =                     =S>                      =                           #",
 "                           =                    =*SSSS**>                 =                           #",
 "                           =                    =*SSSSS*                  =                           #",
 "                           =                    ===  ==                   =                           #",
 "                           =                                              =                           #",
 "                           =                                              =                           #",
 "                           =      INSPIRATION...   Nintendo's             =                           #",
 "                           =                       The Legend of Zelda    =                           #",
 "                           =                                              =                           #",
 "                           =     ttt                                      =                           #",
 "                           =     tt^t                                     =                           #",
 "                           =     tttt                                     =                           #",
 "                           =                                              =                           #",
 "                           ================================================                           #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                            0-Bit  Legend                                             #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                         =====================================================                        #",
 "                         =~~~~                ~~            ~~            ~~~=                        #",
 "                         =~    ~~~   ~~~~~~~~~MM~~~~~M~~~         ~~~~~~     =                        #",
 "                         =  ~~      ~~~~MM~~~MMMM~~~MMM~M~~~~~               =                        #",
 "                         =~~  ~~~~~~~~MMMMMMMMMMMM~MMMMMMM~~MM~~~~~     ~~MMM=                        #",
 "                         =MM~~~      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=                        #",
 "                         =MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...  ...MMMM=                        #",
 "                         =...     .......                   .....   .........=                        #",
 "                         =()......     ... ()......  ..()..()..()()()   ()()(=                        #",
 "                         =()() ()()  ()()..()()..()()()()()  ()   ()()()    (=                        #",
@"                         =()      /\ ()()()()         ()()()     ()()   ()()(=                        #",
@"                         =  ()   |  \ - ()  ()()()()  ()  ()()    ()()()()   =                        #",
 "                         =   XXXX|  ^|-SSS ()()   () ()()()   ()  () ()()()  =                        #",
 "                         = XXXXXX|_=_|-XXX      ()    ()()  ()() ()()()() () =                        #",
 "                         =XXXXXXXXXXXXXXXX ()  ()()()() ()()() ()()  ()()    =                        #",
 "                         =XXXXXXXXXXXXXXX  ()()()()()()()()()()()()()()()()()=                        #",
 "                         =====================================================                        #",

];

    public static string[] WinArmor => [
 "                                  THANKS   LINK,                                                      #",
 "                                  YOU'RE   THE   HERO   OF   HYRULE.                                  #",
 "                                                                                                      #",
@"                                            =<>=    /\                                                #",
 "                                            s^^s   /  |                                               #",
 "                                           ss~~ss |^##|                                               #",
 "                                           ~~~~~~ |#=#|                                               #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                              Awake,  my  young  Hero,                                                #",
 "                              For  peace  waits  not  on  the  morrow.                                #",
 "                              Now  go;  take  this  into  the  unknown:                               #",
 "                              It's  dangerous  to  go  alone!                                         #",
 "                                                                                                      #",
 "                              The  moon  sets,  and  the  moon  rises;                                #",
 "                              Darkness  only  this  night  comprises.                                 #",
 "                              What's  to  hope  with  a  quest  so  foggy?                            #",
 "                              It's  a  secret  to  everybody!                                         #",
 "                                                                                                      #",
 "                              Finally,  peace  returns  to  Hyrule.                                   #",
 "                              And  when  calamity  fell  successful,                                  #",
 "                              The  dream  of  a  legend  lifted  clear:                               #",
 "                              Another  quest  will  start  from  here!                                #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                           ==================== STAFF =====================                           #",
 "                           =                                              =                           #",
 "                           =                                              =                           #",
 "                           =      PRODUCER....     Jayden Newman          =                           #",
 "                           =                                              =                           #",
 "                           =                                              =                           #",
 "                           =      PROGRAMMER.....   Jayden Newman         =                           #",
 "                           =                                              =                           #",
 "                           =                                              =                           #",
 "                           =      DESIGNER....    Jayden Newman           =                           #",
 "                           =                                              =                           #",
 "                           =                                              =                           #",
 "                           =                 <***>                        =                           #",
 "                           =          FFF     S^SSS>                      =                           #",
 "                           =          FFF     *S  SS>                     =                           #",
 "                           =                     =S>                      =                           #",
 "                           =                    =*SSSS**>                 =                           #",
 "                           =                    =*SSSSS*                  =                           #",
 "                           =                    ===  ==                   =                           #",
 "                           =                                              =                           #",
 "                           =                                              =                           #",
 "                           =      INSPIRATION...   Nintendo's             =                           #",
 "                           =                       The Legend of Zelda    =                           #",
 "                           =                                              =                           #",
 "                           =     ttt                                      =                           #",
 "                           =     tt^t                                     =                           #",
 "                           =     tttt                                     =                           #",
 "                           =                                              =                           #",
 "                           ================================================                           #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                            0-Bit  Legend                                             #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                                                                                                      #",
 "                         =====================================================                        #",
 "                         =~~~~                ~~            ~~            ~~~=                        #",
 "                         =~    ~~~   ~~~~~~~~~MM~~~~~M~~~         ~~~~~~     =                        #",
 "                         =  ~~      ~~~~MM~~~MMMM~~~MMM~M~~~~~               =                        #",
 "                         =~~  ~~~~~~~~MMMMMMMMMMMM~MMMMMMM~~MM~~~~~     ~~MMM=                        #",
 "                         =MM~~~      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=                        #",
 "                         =MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...  ...MMMM=                        #",
 "                         =...     .......                   .....   .........=                        #",
 "                         =()......     ... ()......  ..()..()..()()()   ()()(=                        #",
 "                         =()() ()()  ()()..()()..()()()()()  ()   ()()()    (=                        #",
@"                         =()      /\ ()()()()         ()()()     ()()   ()()(=                        #",
@"                         =  ()   |  \ - ()  ()()()()  ()  ()()    ()()()()   =                        #",
 "                         =   XXXX|##^|-SSS ()()   () ()()()   ()  () ()()()  =                        #",
 "                         = XXXXXX|#=#|-XXX      ()    ()()  ()() ()()()() () =                        #",
 "                         =XXXXXXXXXXXXXXXX ()  ()()()() ()()() ()()  ()()    =                        #",
 "                         =XXXXXXXXXXXXXXX  ()()()()()()()()()()()()()()()()()=                        #",
 "                         =====================================================                        #",

];
}
